import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'File Server',
  description: 'Generated by t-saturn team',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
